### ISSUE TITLE
scala_version configuration option not reflected in project

### ISSUE THREAD

**Issue by ghost** [playframework/play-java-seed.g8#27] opened 2018-03-21 21:43 UTC
I created a new project using `sbt new playframework/play-java-seed.g8` and entered options other than the default for the values it asked for.  For scala_version I put 2.11.7 but the generated project used 2.12.4 in build.sbt.  I do not know gitter8 but it appears that line 8 in 'src/main/g8/build.sbt' should be:

scalaVersion := "$scala_version$"

instead of

scalaVersion := "2.12.4"

I can make a PR if you like.

**Comment by mkurz** [comment] 2023-03-02 20:20
This definitely is fixed now:
https://github.com/playframework/play-java-seed.g8/blob/2.8.x/src/main/g8/build.sbt#L8

Also can't reproduce.

**Closed as completed by mkurz** 2023-03-02 20:20 UTC
Labels: status:backlog
